### ISSUE TITLE
How do I use a DataPulse pulse in the prop_capillary function?

### ISSUE THREAD

**Issue by ClaraTey** [LupoLab/Luna.jl#379]
Hi ! I want to change the input pulse in my fiber to a pulse for which I have the spectrum, so I created the pulse with the DataPulse function but I cannot get it to work with the prop_capillary function, it says to me that the DataField as no field field so I'm a bit lost, could you help me?

![Image](https://github.com/user-attachments/assets/f158252f-c68f-4ffb-ae19-2c0201a1c770)

**Comment by chrisbrahms** [comment]
Hi!

I think your problem is the `polarisation=0.57` setting which is trying to create an elliptically polarised pulse (that *is* what you're trying to do, right?). This simply hasn't been implemented for `DataPulse`s on the main branch yet, because of a minor technical difference between `DataPulse`s and the other types. 

I have fixed this on a dev branch here: https://github.com/chrisbrahms/Luna.jl/tree/pulses
It's on my to-do list to finish that up and merge it in the next few weeks. Until then you can check out that branch directly and use it.

**Comment by ClaraTey** [comment]
Hi! 
Thank you for your quick response, that was what I was trying to do, but I tried without putting in any polarisation and I still have the same error unfortunately, might you have an idea of where it comes from?

**Comment by chrisbrahms** [comment]
That's unexpected. To dig deeper I'd need an example script, ideally with the pulse data. Would you be able to upload that here? (you should be able to attach `.txt` files, and you can just copy&paste your code into a comment)

**Comment by ClaraTey** [comment]
Yeah sure thank you for taking the time to deal with this. So here is the script: 

using Pkg
Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("DelimitedFiles")
Pkg.add("Plots")

using Luna

# input pulse parameters
λ0 = 780e-9 # central wavelength, m
τfwhm = 35e-15 # pulse duration FWHM, s
energy = 155e-6 # pulse energy, J

gas= :Ar

# compressor fiber parameters
a_stg1 = 225e-6 # core radius of compressor stage, m

flength_stg1 = 1 # fibre length of compressor stage, m

λlims_stg1 = (200e-9, 4e-6) # grid wavelength limits
trange_stg1 = 1e-12 # time grid size

modes = 3; # number of modes

using DelimitedFiles
using Luna

# Load the file into a matrix (assuming tab-separated)
file_path = "C:/Users/XLC/Desktop/Internship CT March-July 2025/Export code/spectrum measurements/frequency_vacuum2_zeros.txt"
data = readdlm(file_path, '\t')

# Extract frequency, energy, and phase (ensure they are the correct columns)
frequency = data[:, 1]  # Column 1: frequency
energy_density = data[:, 2]  # Column 2: spectral energy density
for element in energy_density
    if element < 0
        element= 0.1
    end
end
phase = data[:, 3]  # Column 3: spectral phase

# Now create the pulse using the processed data
pulse1 = Pulses.DataPulse(frequency, energy_density, phase; energy);

using Plots

labels=["Vacuum","Vacuum","P=0.35 bars","P=0.1 bars","P=0.5 bars","P=0.9 bars","P=1.4 bars","P=1.8 bars","Not taken"]
pressures=[0,0,0.35,0.1,0.5,0.9,1.4,1.8,1.8]

# Plot each spectrum individually
for i in 1:8
    spectrum_col = Symbol("Intensity$i")
    p_stg1 = pressures[i] # gas pressure in compressor stage, bar
    compressor = prop_capillary(a_stg1, flength_stg1, gas, p_stg1;
    λ0,τfwhm, energy , λlims=λlims_stg1, trange=trange_stg1, modes,saveN=2);

And I have uploaded the file that I am using as well.
Thank you so much!

[frequency_vacuum2_zeros.txt](https://github.com/user-attachments/files/19703516/frequency_vacuum2_zeros.txt)

**Comment by chrisbrahms** [comment]
So as you posted it the script runs fine, but you're not using the `pulse1` in the actual simulation. If I insert it, I get a *different* error, this time from the interpolation, because your `frequency` axis is not sorted in increasing order. If I add the following lines:
```julia
sp = sortperm(frequency) # indices which sort by frequency
frequency = frequency[sp]
energy_density = energy_density[sp]
phase = phase[sp]

# Now create the pulse using the processed data
pulse1 = Pulses.DataPulse(frequency, energy_density, phase; energy);
```
then it runs again. Of course adding the `polarisation` back to `pulse1` breaks it again. This will hopefully be fixed on master soon--until feel free to use the branch I posted above.
